@echo off
echo Adding changes to the Git repository...
git add .
echo Changes added successfully.
echo Sleeping for 5 seconds...
ping 127.0.0.1 -n 6 > nul
echo Committing changes...
git commit -m "update"
echo Changes committed successfully.
echo Pushing changes to remote repository...
git push
echo Changes pushed successfully.
